### ISSUE TITLE
git authentication in local development

### ISSUE THREAD

**Issue by andrewpbray** [stat20/stat20-docker#10]
Hi @ryanlovett 

While working locally in a container, when I go to make a commit I get an error asking me to provide user info to sign the commit. I can do so by running.

```
git config --global user.email "andrewbray@berkeley.edu"
git config --global user.name "andrewpbray"
```

To push a commit to github, it prompts me for username and password. I can type those in, but that doesn't work:

```
Username for 'https://github.com': andrewpbray
Password for 'https://andrewpbray@github.com': 
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/stat20/stat20.git/'
```

Normally I store a PAT using this method: <https://happygitwithr.com/https-pat.html>

I could go through that on this session inside the container, but I'm trying to think through the best way to make this a bit more automatic so that a developer doesn't have to configure every time they restart the container.

We started throwing around ideas to solve this but figured it's a good time to circle back to that.

**Comment by ryanlovett** [comment]
@andrewpbray Ah, I thought we settled on using SSH rather than HTTPS for authentication, but my memory is hazy. By using ssh, the developer only needs to auth once since we [proxy](https://github.com/stat20/stat20/blob/main/docker-compose.yml#L14) the ssh agent socket inside the container. If you run `ssh-add -L` from inside, you can see all the same keys you'd see outside of it.

While the user.email and user.name settings are orthogonal to the transport mechanism, we should still document them. Normally git picks these up from ~/.gitconfig, but this is outside of the container. We should probably add a step to [CONTRIBUTING.md](https://github.com/stat20/stat20/blob/main/CONTRIBUTING.md) that one should run ~~`git config --worktree user.email ...`~~ within the working directory at initial setup. I think .gitconfig might also need to be added to .gitignore there too.

**Comment by andrewpbray** [comment]
@ryanlovett Interesting... I entered my git config info, stopped the container, then started it back up again with `make up` and it remembered the config info. Not sure where it's being stored (.gitconfig isn't being tracked by git), but I'm ok with that.

I think you're right about SSH. I went through the happygitwithr docs about setting up SSH keys (which I did from within the container) and put the public one on my github account and when I run `ssh-add -L` I now see the private one. When I got to `git push`, though, I'm still getting the prompt to do username and password, which fails again.

I'll keep cracking at it...

**Comment by ryanlovett** [comment]
My suggestion about `--worktree` was incorrect, and is now struck through.

Perhaps you have the setting saved in `.git/config` ? In which case, it is not part of the working directory so it won't need to be ignored.

If your remote setting (`git remote -v`) has an https URL, you'll need to change it to a git URL in order for it to use SSH. You can run `git remote set-url origin git@github.com:stat20/stat20.git`, if you want to update `origin`. In my case, `origin` is my fork's URL and `upstream` is git@github.com:stat20/stat20.git.
