### ISSUE TITLE
issue with devtools?

### ISSUE THREAD

**Issue by andrewpbray** [stat20/stat20-docker#17]
Hey @ryanlovett (@jeremy-sanchez cc'ed)

I tried to add a new package to image but [got an error](https://github.com/stat20/stat20-docker/actions/runs/8589579455/job/23535890418):

```
Error in download_version_url(package, version, repos, type) : 
#16 56.62   version '1.2.1' is invalid for package 'rsample'
```

I'm puzzled because when I try to install this locally, it looks like it installs that version a-ok.

One potential solution is to swap out this code for Gabor Csardi's new implements in `pak`: [https://pak.r-lib.org/](https://pak.r-lib.org/). Have you used this package before?

**Comment by ryanlovett** [comment]
That version might be incompatible (in terms of dependencies) with the base image plus other libraries in this image. You could try to bump up rocker/verse to 4.3.2 as is on the hub?

When I run `install.packages("rsample")` inside the image, it does pull down 1.2.1, and it fetches it from p3m.dev which is Posit Public Package Manager (pppm). 

When I alternatively run `devtools::install_version('rsample', version='1.2.1')`, it also works. This is surprising since that is what `set_libs` is doing, looping over a package list.

One way of making the R package installs slightly more reproducible is to override the choice of the R repo, changing it from

> https://p3m.dev/cran/__linux__/jammy/latest

to, e.g.

> https://p3m.dev/cran/__linux__/jammy/2024-04-08

Otherwise installs may succeed or fail depending on the day one runs the builds. This is probably a good thing to do regardless.

I haven't used `pak` before. It looks like [one can specify](https://pak.r-lib.org/dev/reference/pkg_install.html#arguments) versions as github tags/branches or as full URLs. Not every package may be maintained on github, and full URLs are usually possible (via posit's package manager) although a bit awkward.

I'll experiment a bit...

**Comment by andrewpbray** [comment]
Huh, ran into this again! I stripped out `rsample` (we found a better base R implementation) but do need `cobalt` and `MatchIt`.

[https://github.com/stat20/stat20-docker/actions/runs/8637072440/job/23678446847](https://github.com/stat20/stat20-docker/actions/runs/8637072440/job/23678446847)

Same error message...

**Comment by andrewpbray** [comment]
btw, looks like we are running 4.3.2

```bash
FROM rocker/verse:4.3.2
```
